/* 1 STORY MAKER — Runtime Patch v9
 * Editable master Google Doc with round-trip synchronization.
 * The Doc stores stable sheet/row markers; DOC_SYNC_BASELINE enables three-way comparison.
 */

var smV8RunNamedAction_ = smRunNamedAction_;

smRunNamedAction_ = function(action){
  var syncMap={
    EXPORT_EDITABLE_MASTER:function(){return smCreateEditableMaster_();},
    SYNC_MASTER_DOC:function(){return smSyncEditableMaster_(false);},
    SYNC_MASTER_AND_REBUILD:function(){return smSyncEditableMaster_(true);}
  };
  if(syncMap[action]){
    try{
      var result=syncMap[action]();
      smLog_(action,'SUCCESS','Editable master Doc workflow completed','');
      return result;
    }catch(err){
      smLog_(action,'FAILED','Editable master Doc workflow failed',err&&err.message?err.message:String(err));
      throw err;
    }
  }
  return smV8RunNamedAction_(action);
};

function smEditableSheetOrder_(){
  return ['STORY','PAYLOAD','AUDIENCE','CHARACTERS','STRUCTURE','LOCATIONS','SCENES','EXPERIENCE','CHARACTER_STATE'];
}

function smCreateEditableMaster_(){
  var folder=smExportVersionFolder_();
  var projectId=String(smControl_('Project ID')||'PROJECT');
  var projectName=String(smControl_('Project Name')||projectId);
  var version=String(smControl_('Story Version')||'0');
  var stamp=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd_HHmmss');
  var title=smSafeFileName_(projectId+' v'+version+' - Editable Story Master - '+stamp);
  var doc=DocumentApp.create(title),docId=doc.getId(),body=doc.getBody();
  smStyleDocumentBody_(body);
  smAppendExportCover_(body,projectId,projectName,version,'Editable Story Master');
  body.appendParagraph('EDITING WORKFLOW').setHeading(DocumentApp.ParagraphHeading.HEADING1).setForegroundColor('#16324F');
  body.appendParagraph('Edit only the Value column. You may add any amount of text to an existing value. Keep the Field names and gray STORYMAKER markers unchanged. After editing, open Story Maker and run SYNC_MASTER_AND_REBUILD. The system compares your edits with the saved baseline, applies changes, runs validation, and regenerates all deliverables.');
  var sheetUrl='https://docs.google.com/spreadsheets/d/'+SM.SPREADSHEET_ID+'/edit#gid=0&range=E26';
  body.appendParagraph('Open Story Maker — Sync & Rebuild').setLinkUrl(sheetUrl).setBold(true).setForegroundColor('#1A73E8');
  body.appendHorizontalRule();

  smEnsureSyncSheets_();
  smClearBaselineForDoc_(docId);
  var baselineRows=[];
  smEditableSheetOrder_().forEach(function(sheetName){
    var rows=smRows_(sheetName);
    if(!rows.length)return;
    body.appendParagraph(smExportSectionTitle_(sheetName)).setHeading(DocumentApp.ParagraphHeading.HEADING1).setForegroundColor('#16324F');
    rows.forEach(function(row,index){
      var sheetRow=index+2;
      body.appendParagraph(smEditableMarker_(sheetName,sheetRow)).setFontSize(8).setForegroundColor('#9CA3AF');
      body.appendParagraph(smExportRowTitle_(sheetName,row,index)).setHeading(DocumentApp.ParagraphHeading.HEADING2).setForegroundColor('#24557A');
      var data=[['Field (do not change)','Value (edit this column)']];
      Object.keys(row).forEach(function(key){
        if(key==='JSON_REF'||key==='JSON_PAYLOAD')return;
        var value=smExportValue_(row[key]);
        data.push([key,value]);
        baselineRows.push([docId,sheetName,sheetRow,key,value,new Date(),[docId,sheetName,sheetRow,key].join('|')]);
      });
      var table=body.appendTable(data);smStyleDataTable_(table);body.appendParagraph('');
    });
  });
  smWriteBaselineRows_(baselineRows);
  body.appendParagraph('Generated by 1. Story Maker — editable master v9').setForegroundColor('#6B7280').setFontSize(8);
  doc.saveAndClose();
  var file=DriveApp.getFileById(docId);file.moveTo(folder);
  var url='https://docs.google.com/document/d/'+docId+'/edit';
  smSetControlIfPresent_('Editable Master Doc',url);
  smSetControlIfPresent_('Last Sync Result','Master created; waiting for edits');
  smRecordExport_({artifactType:'EDITABLE_MASTER',title:title,docId:docId,docUrl:url,folderId:folder.getId(),status:'EDITABLE',error:''});
  return JSON.stringify({doc_id:docId,doc_url:url,folder_url:folder.getUrl()});
}

function smEditableMarker_(sheetName,rowNumber){return '[[STORYMAKER:SHEET='+sheetName+';ROW='+rowNumber+']]';}

function smSyncEditableMaster_(rebuild){
  smEnsureSyncSheets_();
  var docUrl=String(smControl_('Editable Master Doc')||'');
  var match=docUrl.match(/\/document\/d\/([A-Za-z0-9_-]+)/);
  if(!match)throw new Error('CONTROL의 Editable Master Doc에 유효한 Google Doc 링크가 없습니다. 먼저 EXPORT_EDITABLE_MASTER를 실행하세요.');
  var docId=match[1],doc=DocumentApp.openById(docId),body=doc.getBody();
  var baseline=smBaselineMap_(docId),changes=[],conflicts=[],marker=null;
  for(var i=0;i<body.getNumChildren();i++){
    var child=body.getChild(i);
    if(child.getType()===DocumentApp.ElementType.PARAGRAPH){
      var text=child.asParagraph().getText();
      var m=text.match(/^\[\[STORYMAKER:SHEET=([A-Z_]+);ROW=(\d+)\]\]$/);
      if(m)marker={sheet:m[1],row:Number(m[2])};
      continue;
    }
    if(child.getType()!==DocumentApp.ElementType.TABLE||!marker)continue;
    var table=child.asTable(),sh=smSs_().getSheetByName(marker.sheet);
    if(!sh){marker=null;continue;}
    var headers=smHeaders_(sh);
    for(var r=1;r<table.getNumRows();r++){
      var tr=table.getRow(r);if(tr.getNumCells()<2)continue;
      var key=tr.getCell(0).getText().trim();
      var col=headers.indexOf(key)+1;if(col<1)continue;
      var edited=tr.getCell(1).getText();
      var baseKey=[marker.sheet,marker.row,key].join('|');
      var old=Object.prototype.hasOwnProperty.call(baseline,baseKey)?baseline[baseKey]:'';
      var current=smExportValue_(sh.getRange(marker.row,col).getValue());
      if(edited===old)continue;
      if(current!==old&&current!==edited)conflicts.push({sheet:marker.sheet,row:marker.row,field:key,baseline:old,sheet_value:current,doc_value:edited});
      sh.getRange(marker.row,col).setValue(edited);
      changes.push({sheet:marker.sheet,row:marker.row,field:key,before:current,after:edited});
      smUpsertBaseline_(docId,marker.sheet,marker.row,key,edited);
    }
    marker=null;
  }
  smWriteSyncAudit_(docId,changes,conflicts);
  var exportResult='';
  if(rebuild){smScheduleStoryMakerContinuation_('storyMakerContinueBuild');exportResult='BUILD_AND_EXPORT_QUEUED';}
  var summary=changes.length+' fields applied; '+conflicts.length+' conflicts logged'+(rebuild?'; build, validation, and exports queued':'');
  smSetControlIfPresent_('Last Sync Result',summary);
  return JSON.stringify({doc_id:docId,changes:changes.length,conflicts:conflicts.length,rebuild:rebuild,export_result:exportResult});
}

function smScheduleStoryMakerContinuation_(handler){
  ScriptApp.getProjectTriggers().forEach(function(t){
    if(t.getHandlerFunction()===handler)ScriptApp.deleteTrigger(t);
  });
  ScriptApp.newTrigger(handler).timeBased().after(1000).create();
}

function smEnsureSyncSheets_(){
  var ss=smSs_(),base=ss.getSheetByName('DOC_SYNC_BASELINE'),audit=ss.getSheetByName('DOC_SYNC_AUDIT');
  if(!base){
    base=ss.insertSheet('DOC_SYNC_BASELINE');
    base.getRange(1,1,1,7).setValues([['DOC_ID','SHEET','ROW','FIELD','BASE_VALUE','UPDATED_AT','KEY']]);
    smStyleSyncHeader_(base,7);
  }
  base.getRange('E:E').setNumberFormat('@');
  if(!audit){
    audit=ss.insertSheet('DOC_SYNC_AUDIT');
    audit.getRange(1,1,1,10).setValues([['SYNC_ID','SYNCED_AT','DOC_ID','TYPE','SHEET','ROW','FIELD','BEFORE_OR_BASELINE','AFTER_OR_DOC','DETAIL']]);
    smStyleSyncHeader_(audit,10);
  }
}

function smStyleSyncHeader_(sheet,count){
  sheet.setFrozenRows(1);sheet.getRange(1,1,1,count).setBackground('#16324F').setFontColor('#FFFFFF').setFontWeight('bold');sheet.autoResizeColumns(1,count);
}

function smClearBaselineForDoc_(docId){
  var sh=smSs_().getSheetByName('DOC_SYNC_BASELINE'),last=sh.getLastRow();
  if(last<2)return;
  var values=sh.getRange(2,1,last-1,1).getValues(),runs=[],end=null,start=null;
  for(var i=values.length-1;i>=0;i--){
    if(String(values[i][0])===docId){if(end===null)end=i+2;start=i+2;}
    else if(end!==null){runs.push([start,end]);start=null;end=null;}
  }
  if(end!==null)runs.push([start,end]);
  runs.forEach(function(run){sh.deleteRows(run[0],run[1]-run[0]+1);});
}

function smAppendBaseline_(docId,sheet,row,field,value){
  smSs_().getSheetByName('DOC_SYNC_BASELINE').appendRow([docId,sheet,row,field,value,new Date(),[docId,sheet,row,field].join('|')]);
}

function smWriteBaselineRows_(rows){
  if(!rows.length)return;
  var sh=smSs_().getSheetByName('DOC_SYNC_BASELINE');
  sh.getRange(sh.getLastRow()+1,5,rows.length,1).setNumberFormat('@');
  sh.getRange(sh.getLastRow()+1,1,rows.length,7).setValues(rows);
}

function smBaselineMap_(docId){
  var rows=smRows_('DOC_SYNC_BASELINE'),map={};
  rows.forEach(function(x){if(String(x.DOC_ID)===docId)map[[x.SHEET,x.ROW,x.FIELD].join('|')]=smExportValue_(x.BASE_VALUE);});
  return map;
}

function smUpsertBaseline_(docId,sheet,row,field,value){
  var sh=smSs_().getSheetByName('DOC_SYNC_BASELINE'),key=[docId,sheet,row,field].join('|'),last=sh.getLastRow();
  if(last>1){
    var keys=sh.getRange(2,7,last-1,1).getValues();
    for(var i=0;i<keys.length;i++)if(String(keys[i][0])===key){sh.getRange(i+2,5,1,2).setValues([[value,new Date()]]);return;}
  }
  sh.appendRow([docId,sheet,row,field,value,new Date(),key]);
}

function smWriteSyncAudit_(docId,changes,conflicts){
  var sh=smSs_().getSheetByName('DOC_SYNC_AUDIT'),syncId='SYNC_'+Utilities.getUuid(),now=new Date(),rows=[];
  changes.forEach(function(x){rows.push([syncId,now,docId,'APPLIED',x.sheet,x.row,x.field,x.before,x.after,'Doc edit applied']);});
  conflicts.forEach(function(x){rows.push([syncId,now,docId,'CONFLICT_DOC_WON',x.sheet,x.row,x.field,x.baseline,x.doc_value,'Sheet also changed: '+x.sheet_value]);});
  if(!rows.length)rows.push([syncId,now,docId,'NO_CHANGE','','','','','','No document edits detected']);
  sh.getRange(sh.getLastRow()+1,1,rows.length,10).setValues(rows);
}
