/* 1 STORY MAKER — Runtime Patch v8
 * Native Google Docs + PDF artifact export.
 * Keeps Sheets as the editor while producing readable, versioned deliverables in Drive.
 */

var smV7RunNamedAction_ = smRunNamedAction_;

smRunNamedAction_ = function(action){
  var exportMap={
    EXPORT_STORY_DOCS:function(){return smExportArtifactGroups_(['STORY_OVERVIEW']);},
    EXPORT_CHARACTERS_DOCS:function(){return smExportArtifactGroups_(['CHARACTERS']);},
    EXPORT_STRUCTURE_DOCS:function(){return smExportArtifactGroups_(['STRUCTURE']);},
    EXPORT_LOCATIONS_DOCS:function(){return smExportArtifactGroups_(['LOCATIONS']);},
    EXPORT_SCENES_DOCS:function(){return smExportArtifactGroups_(['SCENES']);},
    EXPORT_VALIDATION_DOCS:function(){return smExportArtifactGroups_(['VALIDATION']);},
    EXPORT_FINAL_DOCS:function(){return smExportArtifactGroups_(['FINAL']);},
    EXPORT_ALL_DOCS:function(){return smExportArtifactGroups_(smExportGroupOrder_());},
    BUILD_AND_EXPORT_DOCS:function(){smBuildAll();return smExportArtifactGroups_(smExportGroupOrder_());}
  };
  if(exportMap[action]){
    try{
      var result=exportMap[action]();
      smLog_(action,'SUCCESS','Google Docs/PDF export completed','');
      return result;
    }catch(err){
      smLog_(action,'FAILED','Google Docs/PDF export failed',err&&err.message?err.message:String(err));
      throw err;
    }
  }
  return smV7RunNamedAction_(action);
};

function smExportGroupOrder_(){
  return ['STORY_OVERVIEW','CHARACTERS','STRUCTURE','LOCATIONS','SCENES','VALIDATION','FINAL'];
}

function smExportConfigs_(){
  return {
    STORY_OVERVIEW:{label:'01 Story Overview',sheets:['STORY','PAYLOAD','AUDIENCE']},
    CHARACTERS:{label:'02 Characters',sheets:['CHARACTERS']},
    STRUCTURE:{label:'03 Narrative Structure',sheets:['STRUCTURE']},
    LOCATIONS:{label:'04 Locations',sheets:['LOCATIONS']},
    SCENES:{label:'05 Scenes and Experience',sheets:['SCENES','EXPERIENCE','CHARACTER_STATE']},
    VALIDATION:{label:'06 Validation Report',sheets:['VALIDATION']},
    FINAL:{label:'07 Final Production Bible',sheets:['FINAL']}
  };
}

function smExportArtifactGroups_(groupKeys){
  smEnsureExportsSheet_();
  var root=smExportVersionFolder_();
  var configs=smExportConfigs_();
  var results=[];
  groupKeys.forEach(function(key){
    var cfg=configs[key];
    if(!cfg)return;
    var hasData=cfg.sheets.some(function(name){return smRows_(name).length>0;});
    if(!hasData)return;
    try{
      results.push(smCreateDocPdfArtifact_(key,cfg,root));
    }catch(err){
      smRecordExport_({artifactType:key,title:cfg.label,folderId:root.getId(),status:'FAILED',error:err&&err.message?err.message:String(err)});
      throw err;
    }
  });
  if(!results.length)throw new Error('내보낼 데이터가 없습니다. 먼저 Story Maker 생성 단계를 실행하세요.');
  smSetControlIfPresent_('Last Export Folder',root.getUrl());
  smSetControlIfPresent_('Last Export Result',results.length+' Google Docs + '+results.length+' PDFs');
  return JSON.stringify({folder_url:root.getUrl(),artifacts:results});
}

function smCreateDocPdfArtifact_(artifactType,cfg,folder){
  var projectId=String(smControl_('Project ID')||'PROJECT');
  var projectName=String(smControl_('Project Name')||projectId);
  var version=String(smControl_('Story Version')||'0');
  var stamp=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd_HHmmss');
  var title=smSafeFileName_(projectId+' v'+version+' - '+cfg.label+' - '+stamp);
  var doc=DocumentApp.create(title);
  var docId=doc.getId();
  var body=doc.getBody();
  smStyleDocumentBody_(body);
  smAppendExportCover_(body,projectId,projectName,version,cfg.label);
  cfg.sheets.forEach(function(sheetName){smAppendSheetDataset_(body,sheetName,smRows_(sheetName));});
  body.appendParagraph('Generated by 1. Story Maker').setForegroundColor('#6B7280').setFontSize(8);
  doc.saveAndClose();

  var docFile=DriveApp.getFileById(docId);
  docFile.moveTo(folder);
  var pdfBlob=docFile.getAs(MimeType.PDF).setName(title+'.pdf');
  var pdfFile=folder.createFile(pdfBlob);
  var out={
    artifact_type:artifactType,
    title:title,
    doc_id:docId,
    doc_url:'https://docs.google.com/document/d/'+docId+'/edit',
    pdf_id:pdfFile.getId(),
    pdf_url:pdfFile.getUrl(),
    folder_id:folder.getId(),
    folder_url:folder.getUrl()
  };
  smRecordExport_({
    artifactType:artifactType,title:title,docId:docId,docUrl:out.doc_url,
    pdfId:pdfFile.getId(),pdfUrl:out.pdf_url,folderId:folder.getId(),status:'DONE',error:''
  });
  return out;
}

function smStyleDocumentBody_(body){
  body.setMarginTop(42).setMarginBottom(42).setMarginLeft(48).setMarginRight(48);
}

function smAppendExportCover_(body,projectId,projectName,version,label){
  body.appendParagraph('ALLSTORY UNIVERSE')
    .setHeading(DocumentApp.ParagraphHeading.SUBTITLE)
    .setForegroundColor('#2F6B83');
  body.appendParagraph(label)
    .setHeading(DocumentApp.ParagraphHeading.TITLE)
    .setForegroundColor('#16324F');
  body.appendParagraph(projectName).setHeading(DocumentApp.ParagraphHeading.HEADING1);
  var meta=body.appendTable([
    ['Project ID',projectId],
    ['Story Version',version],
    ['Generated At',Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM-dd HH:mm:ss')],
    ['Source Sheet','https://docs.google.com/spreadsheets/d/'+SM.SPREADSHEET_ID+'/edit']
  ]);
  smStyleKeyValueTable_(meta);
  body.appendHorizontalRule();
}

function smAppendSheetDataset_(body,sheetName,rows){
  body.appendParagraph(smExportSectionTitle_(sheetName))
    .setHeading(DocumentApp.ParagraphHeading.HEADING1)
    .setForegroundColor('#16324F');
  if(!rows.length){
    body.appendParagraph('No data.').setItalic(true).setForegroundColor('#6B7280');
    return;
  }
  rows.forEach(function(row,index){
    var title=smExportRowTitle_(sheetName,row,index);
    body.appendParagraph(title)
      .setHeading(DocumentApp.ParagraphHeading.HEADING2)
      .setForegroundColor('#24557A');
    var data=[['Field','Value']];
    Object.keys(row).forEach(function(key){
      if(key==='JSON_REF'||key==='JSON_PAYLOAD')return;
      var value=smExportValue_(row[key]);
      if(value!=='')data.push([smHumanize_(key),value]);
    });
    if(data.length===1)data.push(['Status','No populated fields']);
    var table=body.appendTable(data);
    smStyleDataTable_(table);
    body.appendParagraph('');
  });
}

function smExportSectionTitle_(sheetName){
  var names={
    STORY:'Story',PAYLOAD:'Payload and Values',AUDIENCE:'Audience',CHARACTERS:'Characters',
    STRUCTURE:'Narrative Structure',LOCATIONS:'Locations',SCENES:'Scenes',EXPERIENCE:'Player Experience',
    CHARACTER_STATE:'Character State Changes',VALIDATION:'Validation',FINAL:'Final Production Dataset'
  };
  return names[sheetName]||smHumanize_(sheetName);
}

function smExportRowTitle_(sheetName,row,index){
  var keys={
    STORY:['PREMISE'],PAYLOAD:['PRIMARY_PAYLOAD'],AUDIENCE:['CREATOR_SELECTED','AI_RECOMMENDED'],
    CHARACTERS:['NAME','CHARACTER_ID'],STRUCTURE:['SECTION_NAME','STRUCTURE_ID'],
    LOCATIONS:['NAME','LOCATION_ID'],SCENES:['TITLE','SCENE_ID'],EXPERIENCE:['SCENE_ID','EXPERIENCE_PROFILE_ID'],
    CHARACTER_STATE:['STATE_ID','SCENE_ID'],VALIDATION:['CHECK_TYPE','VALIDATION_ID'],
    FINAL:['TITLE_NAME','ENTITY_ID']
  };
  var candidates=keys[sheetName]||[];
  for(var i=0;i<candidates.length;i++){
    var value=smExportValue_(row[candidates[i]]);
    if(value)return (index+1)+'. '+smTruncate_(value,120);
  }
  return (index+1)+'. '+smExportSectionTitle_(sheetName);
}

function smStyleKeyValueTable_(table){
  for(var r=0;r<table.getNumRows();r++){
    var row=table.getRow(r);
    row.getCell(0).setBackgroundColor('#E8F0F5');
    row.getCell(0).editAsText().setBold(true).setForegroundColor('#16324F');
    row.getCell(1).editAsText().setForegroundColor('#263746');
  }
}

function smStyleDataTable_(table){
  if(!table.getNumRows())return;
  var header=table.getRow(0);
  for(var c=0;c<header.getNumCells();c++){
    header.getCell(c).setBackgroundColor('#16324F');
    header.getCell(c).editAsText().setBold(true).setForegroundColor('#FFFFFF');
  }
  for(var r=1;r<table.getNumRows();r++){
    var row=table.getRow(r);
    if(r%2===0){for(var j=0;j<row.getNumCells();j++)row.getCell(j).setBackgroundColor('#F3F6F8');}
    row.getCell(0).editAsText().setBold(true).setForegroundColor('#24557A');
  }
}

function smExportVersionFolder_(){
  var sheetFile=DriveApp.getFileById(SM.SPREADSHEET_ID);
  var parentIt=sheetFile.getParents();
  var parent=parentIt.hasNext()?parentIt.next():DriveApp.getRootFolder();
  var root=smGetOrCreateFolder_(parent,'Story Maker Exports');
  var project=smGetOrCreateFolder_(root,smSafeFileName_(String(smControl_('Project ID')||'PROJECT')+' - '+String(smControl_('Project Name')||'Untitled')));
  return smGetOrCreateFolder_(project,'Version '+String(smControl_('Story Version')||'0'));
}

function smGetOrCreateFolder_(parent,name){
  var it=parent.getFoldersByName(name);
  return it.hasNext()?it.next():parent.createFolder(name);
}

function smEnsureExportsSheet_(){
  var ss=smSs_(),sh=ss.getSheetByName('EXPORTS');
  var headers=['EXPORT_ID','CREATED_AT','PROJECT_ID','STORY_VERSION','ARTIFACT_TYPE','TITLE','DOC_ID','DOC_URL','PDF_ID','PDF_URL','FOLDER_ID','STATUS','ERROR'];
  if(!sh){
    sh=ss.insertSheet('EXPORTS');
    sh.getRange(1,1,1,headers.length).setValues([headers]);
    sh.setFrozenRows(1);
    sh.getRange(1,1,1,headers.length).setBackground('#16324F').setFontColor('#FFFFFF').setFontWeight('bold');
    sh.autoResizeColumns(1,headers.length);
    sh.setColumnWidth(6,280);sh.setColumnWidth(8,300);sh.setColumnWidth(10,300);sh.setColumnWidth(13,260);
  }
  return sh;
}

function smRecordExport_(x){
  var sh=smEnsureExportsSheet_();
  sh.appendRow([
    'EXP_'+Utilities.getUuid(),new Date(),smControl_('Project ID')||'',smControl_('Story Version')||'',
    x.artifactType||'',x.title||'',x.docId||'',x.docUrl||'',x.pdfId||'',x.pdfUrl||'',x.folderId||'',x.status||'',x.error||''
  ]);
}

function smSetControlIfPresent_(label,value){
  var map=smControlMap_();
  if(map[label])smSetControl_(label,value);
}

function smExportValue_(value){
  if(value===null||value===undefined||value==='')return '';
  if(Object.prototype.toString.call(value)==='[object Date]')return Utilities.formatDate(value,Session.getScriptTimeZone(),'yyyy-MM-dd HH:mm:ss');
  if(typeof value==='object')return JSON.stringify(value,null,2);
  return String(value);
}

function smHumanize_(key){
  return String(key||'').toLowerCase().split('_').map(function(x){return x?x.charAt(0).toUpperCase()+x.slice(1):'';}).join(' ');
}

function smSafeFileName_(name){
  return String(name||'Untitled').replace(/[\\/:*?"<>|#%{}~]/g,'-').replace(/\s+/g,' ').trim().slice(0,180);
}

function smTruncate_(value,max){
  var s=String(value||'');
  return s.length>max?s.slice(0,max-1)+'…':s;
}

